### PR TITLE
security fixes: fix netmask npm package vulnerable to octal input data

### PR DESCRIPTION
**Pull request by paularah**
This PR adresses issue #146 , packages dependent on netmask@ <=2.0.1 are vulnerable to octal input data. You can read the Github advisory [here](https://github.com/advisories/GHSA-pch5-whg9-qr2r).

### CODE REVIEW

**Comment by Klaitos** [comment]
Need it 🤴

**Comment by Narretz** [comment]
For yarn, you can do this in the meantime:

```
  "resolutions": {
    "node-mailjet/**/netmask": "^2.0.1"
  }
```

Especially since node-mailjet isn't releasing on npm anymore.

**Comment by Narretz** [comment]
Imagine doing a relase after 3 years and not including this simple fix

**Comment by Narretz** [comment]
I wonder why this was closed? Did this dependency get updated somewhere else?

**Comment by Narretz** [comment]
Ah, this was updated in https://github.com/mailjet/mailjet-apiv3-nodejs/commit/cbd96e2ba61094637256572fff1be54daa24e29b

**Pull request closed without merging**
